language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

branches:
  only:
  - master

notifications:
  email: false

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

